services:
  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Main backend port
      - "8002:8002"  # For health check app
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=${MONGODB_URI}  # Use variable from .env
      - REDIS_HOST=${REDIS_HOST}    # Use variable from .env
      - REDIS_PORT=${REDIS_PORT}    # Use variable from .env
      - JWT_SECRET=${JWT_SECRET}    # Use variable from .env
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - CORS_ORIGINS=["http://localhost:3000", "http://${VPS_HOST}", "https://${VPS_HOST}"]  # Allow production host
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}  # Use variable for production API URL
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # MongoDB service
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=taskdb
    networks:
      - app-network
    restart: unless-stopped

  # Redis service
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

  # Nginx service
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb-data:
  redis-data:

networks:
  app-network:
    driver: bridge